---
blank_issues_enabled: false
contact_links:
    - name: 💬 Ask a Question or Start a Discussion
      url: https://github.com/davidbits/FERS/discussions
      about: Please use GitHub Discussions for questions, ideas, and general conversation.
