#!/bin/bash

HOST=darryn
ADDRESS=127.0.0.1
PORT=5678

LOCL_FLDR=$PWD
SRVR_FLDR=/home/darryn/test

FERS_XML_FILENAME=sim.fersxml
FERS_OUTPUT_FILENAME=receiver.h5

scp -P $PORT $LOCL_FLDR/* $HOST@$ADDRESS:$SRVR_FLDR
ssh -X -p $PORT $HOST@$ADDRESS "cd $SRVR_FLDR; fers $FERS_XML_FILENAME"
scp -P $PORT $HOST@$ADDRESS:$SRVR_FLDR/$FERS_OUTPUT_FILENAME $LOCL_FLDR
